export const adminCopy = {
	fa: {
		docTitle: "مدیریت پروژه‌ها | محمد کارگر",
		title: "مدیریت پروژه‌ها",
		subtitle: "افزودن، ویرایش و حذف پروژه‌های سایت",
		projects: "پروژه‌های سایت",
		projectCount: (n: number) => `${n} پروژه`,
		add: "افزودن پروژه",
		edit: "ویرایش",
		delete: "حذف",
		save: "ذخیره",
		cancel: "انصراف",
		lock: "قفل کردن",
		empty: "هنوز پروژه‌ای ثبت نشده است؛ اولین پروژه را اضافه کنید.",
		loading: "در حال بارگذاری…",
		error: "دریافت داده‌ها از سرور ناموفق بود؛ دوباره تلاش کنید.",
		retry: "تلاش دوباره",
		deleteQuestion: "این پروژه حذف شود؟",
		yesDelete: "بله، حذف شود",
		noDelete: "خیر",
		required: "این فیلد اجباری است",
		addTitle: "افزودن پروژه جدید",
		editTitle: "ویرایش پروژه",
		titleFa: "عنوان (فارسی)",
		titleEn: "عنوان (انگلیسی)",
		descriptionFa: "توضیحات (فارسی)",
		descriptionEn: "توضیحات (انگلیسی)",
		role: "نقش",
		websiteLink: "لینک وبسایت",
		sourceCode: "لینک سورس‌کد",
		skills: "مهارت‌ها (با کاما جدا کنید)",
	},
	en: {
		docTitle: "Projects Admin | Mohammad Kargar",
		title: "Manage Projects",
		subtitle: "Add, edit and remove projects of the website",
		projects: "Website projects",
		projectCount: (n: number) => `${n} project${n === 1 ? "" : "s"}`,
		add: "Add project",
		edit: "Edit",
		delete: "Delete",
		save: "Save",
		cancel: "Cancel",
		lock: "Lock",
		empty: "No projects yet — add the first one.",
		loading: "Loading…",
		error: "Couldn't reach the database. Try again.",
		retry: "Retry",
		deleteQuestion: "Delete this project?",
		yesDelete: "Yes, delete",
		noDelete: "No",
		required: "This field is required",
		addTitle: "Add new project",
		editTitle: "Edit project",
		titleFa: "Title (Persian)",
		titleEn: "Title (English)",
		descriptionFa: "Description (Persian)",
		descriptionEn: "Description (English)",
		role: "Role",
		websiteLink: "Website link",
		sourceCode: "Source code link",
		skills: "Skills (comma separated)",
	},
} as const;

export type AdminCopy = (typeof adminCopy)["en"];
