export const vaultCopy = {
	fa: {
		docTitle: "خزانه رمزها | محمد کارگر",
		title: "خزانه رمزها",
		subtitle: "مدیریت امن حساب‌ها و رمزهای عبور",
		restricted: "منطقه خصوصی",
		hint: "برای مشاهده رمزهای ذخیره‌شده، رمز خزانه را وارد کنید.",
		passwordPlaceholder: "رمز خزانه",
		unlock: "ورود به خزانه",
		wrongPassword: "رمز اشتباه است؛ دوباره تلاش کنید.",
		cannotConnect: "ارتباط با سرویس ورود برقرار نشد؛ اتصال اینترنت را بررسی کنید و دوباره تلاش کنید.",
		notConfigured: "خزانه رمزها تنظیم نشده است. متغیرهای VITE_SUPABASE_URL و VITE_SUPABASE_ANON_KEY را در فایل .env تعریف کنید.",
		vaultNotSet: "رمز خزانه هنوز تنظیم نشده است؛ یک ردیف در جدول settings (ستون vault_password) بسازید و دوباره تلاش کنید.",
		credentials: "رمزهای ذخیره‌شده",
		credentialCount: (n: number) => `${n} مورد`,
		add: "افزودن رمز",
		edit: "ویرایش",
		delete: "حذف",
		searchPlaceholder: "جستجو در سرویس یا حساب...",
		empty: "هنوز موردی ذخیره نشده است؛ اولین رمز را اضافه کنید.",
		loading: "در حال بارگذاری…",
		dbError: "دریافت داده‌ها از سرور ناموفق بود؛ دوباره تلاش کنید.",
		retry: "تلاش دوباره",
		service: "سرویس",
		account: "حساب / ایمیل / نام کاربری",
		password: "رمز عبور",
		note: "یادداشت",
		noteOptional: "یادداشت (اختیاری)",
		save: "ذخیره",
		cancel: "انصراف",
		copied: "کپی شد!",
		copyPassword: "کپی رمز",
		showPassword: "نمایش رمز",
		hidePassword: "پنهان‌کردن رمز",
		addTitle: "افزودن رمز جدید",
		editTitle: "ویرایش رمز",
		deleteQuestion: "این رمز حذف شود؟",
		yesDelete: "بله، حذف شود",
		noDelete: "خیر",
		lock: "قفل کردن",
		unlockPrompt: "رمز خزانه را وارد کنید",
		backHome: "بازگشت به صفحه اصلی",
		required: "این فیلد اجباری است",
	},
	en: {
		docTitle: "Credentials Vault | Mohammad Kargar",
		title: "Credentials Vault",
		subtitle: "Keep your accounts and passwords in one place",
		restricted: "Restricted area",
		hint: "Enter the vault password to see your saved credentials.",
		passwordPlaceholder: "Vault password",
		unlock: "Unlock vault",
		wrongPassword: "Wrong password, try again.",
		cannotConnect: "Couldn't reach the sign-in service. Check your connection and try again.",
		notConfigured: "The vault is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your .env file.",
		vaultNotSet: "The vault password is not set yet — insert a row in the settings table (vault_password column) and try again.",
		credentials: "Saved credentials",
		credentialCount: (n: number) => `${n} item${n === 1 ? "" : "s"}`,
		add: "Add credential",
		edit: "Edit",
		delete: "Delete",
		searchPlaceholder: "Search service or account...",
		empty: "Nothing saved yet — add your first credential.",
		loading: "Loading…",
		dbError: "Couldn't reach the vault database. Try again.",
		retry: "Retry",
		service: "Service",
		account: "Account / Email / Username",
		password: "Password",
		note: "Note",
		noteOptional: "Note (optional)",
		save: "Save",
		cancel: "Cancel",
		copied: "Copied!",
		copyPassword: "Copy password",
		showPassword: "Show password",
		hidePassword: "Hide password",
		addTitle: "Add new credential",
		editTitle: "Edit credential",
		deleteQuestion: "Delete this credential?",
		yesDelete: "Yes, delete",
		noDelete: "No",
		lock: "Lock",
		unlockPrompt: "Enter vault password",
		backHome: "Back to home",
		required: "This field is required",
	},
} as const;

export type VaultCopy = (typeof vaultCopy)["en"];
